use ferrum_platform::ubuntu::{RULES_V4, RULES_V6};
use ferrum_platform::{Platform, PlatformError};
use std::path::Path;

/// Which of the host's own persisted rulesets exist, whether or not anything had to be opened.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Persisted {
    pub v4: bool,
    pub v6: bool,
}

impl Persisted {
    pub fn any(self) -> bool {
        self.v4 || self.v6
    }
}

/// The ports among `wanted` that a persisted INPUT chain rejects; `None` when nothing is rejected
/// or the file is ufw's own save.
pub fn blocked(rules: &str, wanted: &[u16]) -> Option<Vec<u16>> {
    if rules.contains("ufw-") {
        return None;
    }
    let mut accepted: Vec<u16> = Vec::new();
    for line in rules.lines().map(str::trim) {
        if !line.starts_with("-A INPUT") {
            continue;
        }
        if is_terminal(line) {
            let missing: Vec<u16> = wanted
                .iter()
                .copied()
                .filter(|p| !accepted.contains(p))
                .collect();
            return Some(missing);
        }
        if line.ends_with("-j ACCEPT") {
            accepted.extend(ports_of(line));
        }
    }
    None
}

/// Inserts one ACCEPT for `ports` immediately before the first REJECT or DROP in INPUT.
pub fn with_ports(rules: &str, ports: &[u16]) -> String {
    let list = ports
        .iter()
        .map(u16::to_string)
        .collect::<Vec<_>>()
        .join(",");
    let accept =
        format!("-A INPUT -p tcp -m state --state NEW -m multiport --dports {list} -j ACCEPT");
    let mut out = String::with_capacity(rules.len() + accept.len() + 1);
    let mut inserted = false;
    for line in rules.split_inclusive('\n') {
        let trimmed = line.trim();
        if !inserted && trimmed.starts_with("-A INPUT") && is_terminal(trimmed) {
            out.push_str(&accept);
            out.push('\n');
            inserted = true;
        }
        out.push_str(line);
    }
    out
}

/// Opens `ports` in both persisted rulesets and applies the ones that changed.
pub fn ensure_open(platform: &dyn Platform, ports: &[u16]) -> anyhow::Result<Persisted> {
    Ok(Persisted {
        v4: open_family(platform, RULES_V4, ports, |r| platform.iptables_restore(r))?,
        v6: open_family(platform, RULES_V6, ports, |r| platform.ip6tables_restore(r))?,
    })
}

fn open_family(
    platform: &dyn Platform,
    path: &str,
    ports: &[u16],
    restore: impl Fn(&str) -> Result<(), PlatformError>,
) -> anyhow::Result<bool> {
    let Some(rules) = platform.read_file(Path::new(path))? else {
        return Ok(false);
    };
    let Some(missing) = blocked(&rules, ports) else {
        return Ok(false);
    };
    if missing.is_empty() {
        return Ok(true);
    }
    let opened = with_ports(&rules, &missing);
    platform.write_file(Path::new(path), &opened, 0o644)?;
    restore(&opened)?;
    Ok(true)
}

fn is_terminal(line: &str) -> bool {
    line.ends_with("-j REJECT")
        || line.contains("-j REJECT ")
        || line.ends_with("-j DROP")
        || line.contains("-j DROP ")
}

fn ports_of(line: &str) -> Vec<u16> {
    let mut words = line.split_whitespace();
    while let Some(word) = words.next() {
        if word == "--dport" || word == "--dports" {
            return words
                .next()
                .unwrap_or_default()
                .split(',')
                .filter_map(|p| p.parse().ok())
                .collect();
        }
    }
    Vec::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ferrum_platform::FakePlatform;

    const ORACLE: &str = "# Generated by iptables-save v1.8.7 on Tue Sep  1 10:00:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:InstanceServices - [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p udp --sport 123 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OUTPUT -d 169.254.0.0/16 -j InstanceServices
COMMIT
";

    const ORACLE_V6: &str = "# Generated by ip6tables-save v1.8.7 on Tue Sep  1 10:00:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p ipv6-icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p udp --sport 123 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp6-adm-prohibited
-A FORWARD -j REJECT --reject-with icmp6-adm-prohibited
COMMIT
";

    #[test]
    fn oracle_rejects_the_web_ports_but_not_ssh() {
        assert_eq!(blocked(ORACLE, &[22, 80, 443]), Some(vec![80, 443]));
        assert_eq!(blocked(ORACLE, &[22]), Some(vec![]));
        assert_eq!(blocked(ORACLE_V6, &[22, 80, 443]), Some(vec![80, 443]));
    }

    #[test]
    fn a_ruleset_without_a_terminal_rule_and_ufws_own_save_are_left_alone() {
        assert_eq!(
            blocked("*filter\n-A INPUT -i lo -j ACCEPT\nCOMMIT\n", &[80]),
            None
        );
        let ufw = "*filter\n-A INPUT -j ufw-before-input\n-A INPUT -j REJECT\nCOMMIT\n";
        assert_eq!(blocked(ufw, &[80]), None);
    }

    #[test]
    fn the_accept_lands_before_the_reject_and_nothing_else_moves() {
        let opened = with_ports(ORACLE, &[80, 443]);
        let accept =
            "-A INPUT -p tcp -m state --state NEW -m multiport --dports 80,443 -j ACCEPT\n";
        let reject = "-A INPUT -j REJECT --reject-with icmp-host-prohibited\n";
        assert_eq!(opened.matches(accept).count(), 1);
        assert!(opened.find(accept).unwrap() < opened.find(reject).unwrap());
        assert_eq!(opened.replacen(accept, "", 1), ORACLE);
        assert_eq!(blocked(&opened, &[22, 80, 443]), Some(vec![]));
        assert!(opened.contains("-m multiport --dports 80,443 -j ACCEPT\n-A INPUT -j REJECT"));
    }

    #[test]
    fn ensure_open_writes_restores_and_is_idempotent() {
        let p = FakePlatform::new();
        assert_eq!(ensure_open(&p, &[80, 443]).unwrap(), Persisted::default());
        assert!(p.calls_matching("iptables_").is_empty());
        assert!(p.calls_matching("ip6tables_").is_empty());
        assert!(p.calls_matching("write_file").is_empty());

        p.write_file(Path::new(RULES_V4), ORACLE, 0o644).unwrap();
        let opened = ensure_open(&p, &[2222, 80, 443]).unwrap();
        assert!(opened.v4 && !opened.v6);
        let written = p.written(RULES_V4).unwrap();
        assert!(
            written.contains("--dports 2222,80,443 -j ACCEPT"),
            "{written}"
        );
        assert_eq!(p.calls_matching("iptables_restore").len(), 1);
        assert!(p.calls_matching("ip6tables_").is_empty());
        assert!(p.written(RULES_V6).is_none());

        assert!(ensure_open(&p, &[2222, 80, 443]).unwrap().v4);
        assert_eq!(p.calls_matching("iptables_restore").len(), 1);
        assert_eq!(p.written(RULES_V4).unwrap(), written);
    }

    #[test]
    fn a_v6_ruleset_is_opened_through_ip6tables() {
        let p = FakePlatform::new();
        p.write_file(Path::new(RULES_V6), ORACLE_V6, 0o644).unwrap();
        let opened = ensure_open(&p, &[80, 443]).unwrap();
        assert!(!opened.v4 && opened.v6);
        assert!(opened.any());
        assert!(
            p.written(RULES_V6)
                .unwrap()
                .contains("--dports 80,443 -j ACCEPT\n-A INPUT -j REJECT --reject-with icmp6")
        );
        assert_eq!(p.calls_matching("ip6tables_restore").len(), 1);
        assert!(p.calls_matching("iptables_").is_empty());
    }
}
