[package]
name = "ferrum"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ferrum"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
