[package]
name = "ferrum-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
ferrum-platform = { path = "../ferrum-platform" }
hickory-resolver.workspace = true
hmac.workspace = true
instant-acme.workspace = true
octocrab.workspace = true
rand.workspace = true
rcgen.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true
x509-parser.workspace = true
sqlx.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util"] }
